### ISSUE TITLE
Action does not support variable parameters

### ISSUE THREAD

**Issue by christoph-morrison** [fhem/fhem-controls-actions#8]
The following definition [did not work](https://github.com/christoph-morrison/FHEM-Icons-Material/actions/runs/447625446) (excerpt):
```
    env:
      CHANGED_FILE: CHANGED
      CONTROLS_FILE: controls_icons-material.txt
      FILES_DIR: www/icons/material
[...]
      - name: Create FHEM controlfile
        uses: fhem/fhem-controls-actions@master
        with:
          filename: $CONTROLS_FILE
          directory: $FILES_DIR
          extension: .svg
```

But using non-variable data, [worked](https://github.com/christoph-morrison/FHEM-Icons-Material/actions/runs/447633584) (excerpt):
```
      - name: Create FHEM controlfile
        uses: fhem/fhem-controls-actions@master
        with:
          filename: controls_icons-material.txt
          directory: www/icons/material
          extension: .svg
```

fhem-controls-action should support variable parameters.

**Comment by sidey79** [comment]
I think this is not a bug in the action itself, it's more an limitation of github actions overall, that environment variables only exists during runtime and not in the yaml interpreter.

https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#about-environment-variables

But i think you can specify the variable from the env section also:

```
      - name: Create FHEM controlfile
        uses: fhem/fhem-controls-actions@master
        with:
          filename: ${{ env.CONTROLS_FILE }}
          directory: ${{ env.FILES_DIR }}
          extension: .svg
```

Not sure, if this works if the env statement is also inside the same step or if it must be general to the job.
